### ISSUE TITLE
tests failing w/ python 3.9

### ISSUE THREAD

**Issue by gfudenberg** [open2c/polychrom#40]
Can't pickle local object 'averageContacts.<locals>.<lambda>'

![image](https://user-images.githubusercontent.com/19657573/114582459-767c7600-9c35-11eb-9961-4dd1d819bef3.png)

Still pass with 3.7

**Comment by mimakaev** [comment]
hm. That looks complicated. And python 3.9 is coming up. I'll take a look at some point...

**Comment by mimakaev** [comment]
![image](https://user-images.githubusercontent.com/9454715/114801087-04a54900-9d69-11eb-9ca3-47436f02e251.png)
So weird: on my laptop it passes all tests with python 3.9

**Comment by mimakaev** [comment]
@gfudenberg - is this in your branch? Did you switch github actions to test on the grid? 

Also, github actions is using openmm from omnia... while openmm moved to conda-forge, and now pulls 1GB cuda package with it. Maybe there is a way to disable the 1GB package... that would suck on a grid...

**Comment by gfudenberg** [comment]
strange! 
I was getting this error on the open2c/master branch (and it didn't go away on my branch) on my laptop after the following:
- create new conda environment with numpy and cython
- install openmm with conda
- install pytest with pip
- install polychrom with pip install -e ./
- run pytest ./tests/

also! on my laptop (with python3.9 at least, can't remember for 3.7), the conda install -c omnia openmm  listed in our docs no longer works (segfaults), but the conda install -c conda-forge openmm listed on the openmm docs seems to work fine.
