### ISSUE TITLE
Continuing a simulation

### ISSUE THREAD

**Issue by itsameerkat** [open2c/polychrom#44]
Currently the protocol for continuing a simulation has a shortcoming - When we recreate the _Simulation_ instance, it reinitializes  _self.time = 0_ and _self.block = 0_. https://github.com/itsameerkat/polychrom/blob/a3a39290857bc889627f9d437faa050248bbdc13/polychrom/simulation.py#L326-L328

The HDF5 files that contains the outputs are fine because _HDF5Reporter.continue_trajectory()_ informs the reporter of the block from which it should resume reporting. https://github.com/itsameerkat/polychrom/blob/a3a39290857bc889627f9d437faa050248bbdc13/polychrom/hdf5_format.py#L305

I propose that we update the _Simulation_ class so that it infers _self.time_ and _self.block_ from the reporter that is passed to it.

**Comment by itsameerkat** [comment]
While attempting to figure out a solution, I got confused by _HDF5Reporter_ structure. 

**Current Understanding of the Structure:**
_HDF5Reporter()_ has a list _self.prefixes_ that serve as filenames of different outputs. The class also has _self.counter_ which is a dictionary that keeps track of how many files associated with a particular prefix have been generated. When HDF5Reporter.report() is called with _name_ and _value_: 1) The _count_ associated with _name_ in _self.counter_ is accessed and a .h5 file with filename _{name}_{count}.h5_ is created the information in _value_ is stored there and 2) _self.counter[name]_ is incremented.

**Observation:**
One of the items in _self.prefixes_ is _"blocks"_. I initially assumed that this prefix was associated with the output files named _blocks*-*.h5_ that  contain the data generated at each (reported) simulation step. Thus when outputs are being saved,  _HDF5Reporter.report()_ is called with _name="blocks"_ and _value_ being a dictionary of positions, kinetic energy, potential energy etc. However, this is not the case - the actual prefix associated with output files named _blocks*-*.h5_ is _"data"_. _"data"_ is not an item in _self.prefixes_ but is passed to _HDF5Reporter.report()_ as the _name_ argument whenever _Simulation.do_block()_ is called.

**Inconsistency:**
1) All output files are generated using items from _self.prefixes_ except the actual simulation output. Why is it done this way?
2) Unlike all the other items in  _self.prefixes_, the _"blocks"_ item is not used to generate files that have names starting with "blocks". This seems inconsistent. 
3) Because _"blocks"_ is not used to generate _blocks*-*.h5_ files, the count associated with it in _self.counter_ will always be zero. <img width="1013" alt="Screen Shot 2021-09-16 at 7 20 56 PM" src="https://user-images.githubusercontent.com/26881078/133697708-22104504-3858-4813-987d-441dd047f33d.png">
4) The only time that _"blocks"_ seems to used is if _overwrite=True_ or _check_exists=True_ when _HDF5Reporter_ is being initialized.


It seems to be that  _"data"_ and _"blocks"_ serve overlapping purposes and I don't think we need to keep both. I propose that we stop using _"data"_ altogether and associate _"blocks"_ with reporting simulation outputs.

**Comment by itsameerkat** [comment]
@mimakaev @gfudenberg

**Comment by mimakaev** [comment]
self.block was a historical name for a block number of a simulation. When writing code to continue a simulation, I worried about a reporter and did not add provisions to update time and block. It can be done in the continue_simulation code. I rarely use the code to continue something, and when I do I set a block number manually. 

"blocks" in self.prefixes serves a different purpose: checking if there is a file in the trajectory, in the code that prevents overwriting an existing trajectory.  Hence it was added there. 

I don't have a clear decision whether I we should be passing a single block under a key "block", or under a key "data". I'm against passing a single block of data under key "blocks" - that seems inconsistent.

**Comment by itsameerkat** [comment]
So currently there is no function associated with "continue_simulation". AFAIK, the prescription to continue is a simulation is to initialize a_HDF5Reporter()_ instance, update it state using _reporter.continue_trajectory()_ and then pass the updated reporter when initializing a new instance of _Simulation()_. However, the _Simulation_ class always initializes _self.block = 0_ and _self.time = 0_.

The minimal change would be to allow self.blocks and self.time to be initialized by the user. _reporter.continue_trajectory()_ returns information about latest block, time and conformation. Currently the only the conformation is passed to the simulation object. I propose that we allow block and time to be passed to it as well.

**Comment by itsameerkat** [comment]
I personally don't mind passing "blocks" to _reporter.report()_ when reporting a single block of simulation output. Yes it is inconsistent but only in the semantics.

I'd be curious to hear what other thinks.
