### ISSUE TITLE
bug in polychrom/examples/loopExtrusion/extrusion_3D

### ISSUE THREAD

**Issue by henr7110** [open2c/polychrom#47]
run extrusion_3D fails with the following error:
![image](https://user-images.githubusercontent.com/31934917/163037147-266bbbf5-f6dd-4250-bba5-e8db3065b6f0.png)

I suspect it is a bug in block 4 line 25 which currently says: chains=[(0, None, None)], and should probably be changed to chains=[(0, None, False)]. I have already run extrusion_1D_newCode, and the whole thing seems to run if None is changed to False.

**Comment by mimakaev** [comment]
@henr7110  - is this fixed now? Can I close?

**Comment by henrik-dahl-pinholt** [comment]
When the pull request is accepted it should be fixed
