### ISSUE TITLE
Enforcing chromosome territories

### ISSUE THREAD

**Issue by b2jia** [open2c/polychrom#48]
What's an appropriate protocol for enforcing chromosome territories (ie. if we have 2 copies of `chr1`, then the two fibers reside in distinct locations in the nucleus)?

My question is: is this built-in to the simulation, or must we specify the chromosome "anchors" explicitly? If the latter, what's an appropriate protocol for enforcing chromosome territories - is it to do Poisson disc sampling and anchor _N_ positions, which can we can tether (eg. `forcekits.force.tether_particles(sim, particles=[pos_anchor, index_of_fiber_to_anchor])`?

**Comment by mimakaev** [comment]
To the best of my knowledge, the easiest way to enforce chromosome territories is to disable or strongly restrict chains passing, and then start with compact chromosomes located where you think they are. If two sister chromosomes are aligned (e.g. Drosophila), then you start with the two condensed chromosomes parallel to each other. If not, you start with two condensed chromosomes in two different locations of the nucleus. 

It will be a non-equilibrium simulation, which is more difficult to work with than an equilibrium simulation. But this is likely very close to truth: chromosomes are likely out of equilibrium, as mixing times were estimated to be on the order of years if not more.

**Comment by b2jia** [comment]
> If not, you start with two condensed chromosomes in two different locations of the nucleus.

I see, sounds like tethering to a specified location is the way to go

**Comment by b2jia** [comment]
I tried seeding fixed positions to which I `tether`ed the monomer closest to the center of mass, but to no avail. Here are two chromatin fibers that should ideally be spatially separable:
![image](https://user-images.githubusercontent.com/37123556/163927338-0882b97b-2b42-4f79-9397-1492d59ce717.png)

Ideas that I've produced to achieve this "fractal"-like state include:
- [ ] utilize `forces.selective_SSW` to specify cis-fiber monomers as stickyParticles and trans-fiber (other homolog) as extraHardParticles
- [ ] add "polar" forces (ie. `forces.pull_force`) so that each territory are pulled to opposite poles of the nucleus (... not sure if this is biological)

I also tried pairing sister-chromatid-like fibers as well with `forces.harmonic_bonds` specifying pairs of corresponding monomers, but for some reason this rarely produces parallel "train-track" like fibers. Would love to know how to recapitulate the transvection event in Drosophila as well.

**Comment by mimakaev** [comment]
We are scheduled to discuss this today. Please wait till then. This is not an issue with polychrom. What you are asking for is advising regarding developing models for polychrom. Closing this issue, since it's best to keep things in relevant forums.
