### ISSUE TITLE
[question] Stiffness parameter in `polychrom.forces.angle_force`

### ISSUE THREAD

**Issue by b2jia** [open2c/polychrom#49]
Regarding `polychrom.forces.angle_force`, the stiffness parameter `k` is currently in units of kT. Is there a way to interpret (or convert) this in terms of bond-lengths? 

At the moment I'm having trouble interpreting just how "stiff" `k`= 1, and to me, a more intuitive definition might be specifying this in terms of bond lengths (or even base-pairs). It seems in addition to this ambiguity, `k` is a function of some parameter `alpha` which is neither a parameter in the actual function, nor is it explicitly defined in the documentation.

> k (float or list of length N) – Stiffness of the bond. If list, then determines the stiffness of the i-th triplet Potential is k * alpha^2 * 0.5 * kT

Thanks in advance for the clarification.

**Comment by mimakaev** [comment]
It is not always trivial how stiffness is converted to persistence length. E.g. it may depend on the exact parameters on polymer bonds. 

alpha is an angle. Potential energy is $U=\alpha^2 * k * kT * 0.5$  - it's a quadratic function of angle, with a coefficient of $k * kT / 2$
